---

- hosts: local

  tasks:
    - name: Gather facts from test servers
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['test'] }}"

- hosts: test
  serial: 1

  tasks:
    - name:  ansible_host is the host exec the task
      debug:
        var:  ansible_host

    - name: Recursively copy files from management server to target
      local_action: ansible.builtin.command rsync -a /tmp/ {{ inventory_hostname }}:/tmp/

    - name: Send summary mail
      local_action:
        module: community.general.mail
        subject: "Summary Mail"
        to: "13533403095@163.com"
        body: "hello world."
      run_once: True

    - name: Take out of load balancer pool
      ansible.builtin.command: /usr/bin/take_out_of_pool {{ inventory_hostname }}
      delegate_to: 127.0.0.1

    - name: Actual steps would go here
      ansible.builtin.yum:
        name: acme-web-stack
        state: latest

    - name: Add back to load balancer pool
      ansible.builtin.command: /usr/bin/add_back_to_pool {{ inventory_hostname }}
      delegate_to: 127.0.0.1