---
- name: test loops
  hosts: corptest
  serial: 1
  gather_facts: False
  vars:
    items:
      - cat
      - dog

  tasks:
    - name: Count our fruit
      ansible.builtin.debug:
        msg: "{{ item }} with index {{ my_idx }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        index_var: my_idx
# 外部的1、2、3对应inner每一遍
    - include_tasks: inner.yml
      loop:
        - 1
        - 2
        - 3
      loop_control:
        loop_var: outer_item
    
    - name: Extended loop variables
      debug:
        msg: "{{ansible_loop.allitems}}"
      loop:
        - one
        - two
      loop_control:
        extended: yes

    - name: Extended loop variables
      debug:
        msg: "{{ansible_loop_var}}" # is item
      loop:
        - one
        - two
      loop_control:
        extended: yes

    - name: with_items
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: "{{ items }}"
    
    - name: with_items -> loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ items|flatten(levels=1) }}"

    - name: with_indexed_items
      ansible.builtin.debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      with_indexed_items: "{{ items }}"
    
    - name: with_indexed_items -> loop
      ansible.builtin.debug:
        msg: "{{ index }} - {{ item }}"
      loop: "{{ items|flatten(levels=1) }}"
      loop_control:
        index_var: index